services:
  caddy:
    build: ./caddy
    image: local-caddy:latest
    ports:
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    environment:
      - SITE_HOSTNAME=${SITE_HOSTNAME:-localhost}
  rails:
    build: ./rails
    command: >
      bash -lc "bundle check || bundle install && rm -f tmp/pids/server.pid && bundle exec rails server -b 0.0.0.0 -p 3000"
    volumes:
      - .:/app:delegated
      - vendor_bundle:/app/rails/vendor/bundle
    working_dir: /app/rails
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/app/rails/vendor/bundle
      - SITE_HOSTNAME=${SITE_HOSTNAME:-localhost}
      - COPI_ADMIN_PASSWORD=${COPI_ADMIN_PASSWORD:-}
    user: "${USR:-root}"
  copilot:
    build: ./copilot
    environment:
      - HOME=/homedir
      - GITHUB_TOKEN=${COPILOCA_GITHUB_TOKEN:-}
    restart: unless-stopped
    volumes:
      - ${COPILOCA_APP_PATH:-.}:/app:delegated
      - copilot_home:/homedir
      - ./rails/tmp:/shared-tmp:delegated
    working_dir: /app
    user: "${USR:-root}"

volumes:
  caddy_data:
  caddy_config:
  vendor_bundle:
  copilot_home:
